### ISSUE TITLE
Add support for extra XML-RPC errors

### ISSUE THREAD

**Issue by piranna** [claudijo/json-rpc-error#1]
JsonRPC errors are based on XML-RPC ones, but this last ones has defined some more extra codes. Add entries for them.

**Comment by claudijo** [comment]
Thanks for the feedback. This package only includes error codes from the JSON RPC 2 spec. If you need custom XML-RPC type fault codes, I would suggest to use the general base constructor for JSON RPC 2 errors:  `new JsonRpcError(message, code[, data]);`

**Comment by piranna** [comment]
Being both compatible (in fact, json rpc ones are borrowed from xml rpc ones) I though it would make sense to expand them...
