### ISSUE TITLE
Rpc Error -18

### ISSUE THREAD

**Issue by FiatVoluntas** [claudijo/json-rpc-error#2]
I've been trying to install (and am very new to this) joinmarket through the terminal but when trying to display the addresses for my wallet I keep getting this error code:

+++jmclient.jsonrpc.JsonRpcError: {'code': -18, 'message': 'No wallet is loaded. Load a wallet using loadwallet or create a new one with createwallet. (Note: A default wallet is no longer automatically created)'}+++

Any idea what could be wrong?  I apologize if this is a simple fix, again, I'm very new to this and have never really done any programming/terminal work before.  If possible I'd like to install joinmarket qt. but am getting this code that may be connected in some way to my previous issue mentioned above:

+++Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)+++

**Comment by claudijo** [comment]
Sorry @FiatVoluntas , I wish I could help you but the issue is not related to this project. 

This project is just a minimal convenience library to create and format errors according to the JSON RPC protocol. You need to look downstream to find what project is actually creating the error "No wallet is loaded...". Good luck!
